// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject

package main

import (
	"telegram-bot/src/modules/telegram"
	"telegram-bot/src/modules/tiktok"
)

func initBot(token, baseURL string) (*telegram.Bot, error) {
	client := tiktok.NewClient(baseURL)
	service := tiktok.NewService(client)
	cache := telegram.NewCache()
	bot, err := telegram.NewBot(token, service, cache)
	if err != nil {
		return nil, err
	}
	return bot, nil
}
