// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire

//go:build !wireinject

package main

import (
	"telegram-bot/src/modules/downloader"
	"telegram-bot/src/modules/telegram"
)

func initBot(token string, cfg downloader.Config) (*telegram.Bot, error) {
	tikTokClient := downloader.NewTikTokClient(cfg)
	tikTokService := downloader.NewTikTokService(tikTokClient)
	cobaltClient := downloader.NewCobaltClient(cfg)
	instagramService := downloader.NewInstagramService(cobaltClient, cfg)
	facebookService := downloader.NewFacebookService(cobaltClient, cfg)
	router := downloader.NewRouter(tikTokService, instagramService, facebookService)
	cache := telegram.NewCache()
	bot, err := telegram.NewBot(token, router, cache)
	if err != nil {
		return nil, err
	}
	return bot, nil
}
